import paramiko, sys
sys.stdout.reconfigure(encoding='utf-8')
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect('connect.bjb1.seetacloud.com', port=50405, username='root', password='roBbKv+ed3Vm', timeout=15)
def run(cmd):
    stdin, stdout, stderr = client.exec_command(cmd)
    return stdout.read().decode('utf-8', errors='replace').strip()
print('Log tail:')
print(run('tail -30 /root/autodl-tmp/sim_cpu.log 2>/dev/null'))
print('---')
print('Samples count:')
print(run('ls /root/autodl-tmp/streetview_sim/samples/ 2>/dev/null | wc -l'))
print('files')
print('---')
print('Running processes:')
stdin2, stdout2, stderr2 = client.exec_command('ps aux | grep sim_run_cpu')
print(stdout2.read().decode('utf-8', errors='replace').strip())
client.close()