import paramiko, sys
sys.stdout.reconfigure(encoding='utf-8')
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect('connect.bjb1.seetacloud.com', port=50405, username='root', password='roBbKv+ed3Vm', timeout=15)
def run(cmd):
    stdin, stdout, stderr = client.exec_command(cmd)
    return stdout.read().decode('utf-8', errors='replace').strip()
print('=== sim_out.log (last 30 lines) ===')
print(run('tail -30 /root/autodl-tmp/sim_out.log'))
print('---')
print('=== sim_run_cpu.py first 50 lines ===')
print(run('head -50 /root/autodl-tmp/sim_run_cpu.py'))
print('---')
print('=== streetview_sim directory ===')
print(run('ls -la /root/autodl-tmp/streetview_sim/'))
print('---')
print('=== samples dir count ===')
print(run('ls /root/autodl-tmp/streetview_sim/samples/ 2>/dev/null | wc -l'))
client.close()