import paramiko, sys
sys.stdout.reconfigure(encoding='utf-8')
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect('connect.bjb1.seetacloud.com', port=50405, username='root', password='roBbKv+ed3Vm', timeout=15)
def run(cmd):
    stdin, stdout, stderr = client.exec_command(cmd)
    return stdout.read().decode('utf-8', errors='replace').strip()
print('All python processes:')
print(run('ps aux | grep python'))
print('---')
print('autodl-tmp contents:')
print(run('ls -la /root/autodl-tmp/'))
print('---')
print('Log file details:')
print(run('ls -la /root/autodl-tmp/sim_cpu.log 2>/dev/null'))
print(run('wc -l /root/autodl-tmp/sim_cpu.log 2>/dev/null'))
print('---')
print('First 20 lines of log:')
print(run('head -20 /root/autodl-tmp/sim_cpu.log 2>/dev/null'))
print('---')
print('Any .py files in autodl-tmp:')
print(run('find /root/autodl-tmp -name " *.py\ -type f 2>/dev/null'))
print('---')
print('Recent auth.log (last 20 lines):')
print(run('tail -20 /var/log/auth.log 2>/dev/null'))
client.close()